/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvertisingIndexRouteImport } from './routes/advertising/index'
import { Route as ToolsWhiteListRouteImport } from './routes/tools/white-list'
import { Route as DmpCrowdListRouteImport } from './routes/dmp/crowd-list'
import { Route as CrowdManageRouteImport } from './routes/crowd/manage'
import { Route as AnalyticsFlowAnalysisRouteImport } from './routes/analytics/flow-analysis'
import { Route as AdvertisingPlanRouteImport } from './routes/advertising/plan'
import { Route as AdvertisingCampaignRouteImport } from './routes/advertising/campaign'
import { Route as AdvertisingAdvertisersRouteImport } from './routes/advertising/advertisers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingIndexRoute = AdvertisingIndexRouteImport.update({
  id: '/advertising/',
  path: '/advertising/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWhiteListRoute = ToolsWhiteListRouteImport.update({
  id: '/tools/white-list',
  path: '/tools/white-list',
  getParentRoute: () => rootRouteImport,
} as any)
const DmpCrowdListRoute = DmpCrowdListRouteImport.update({
  id: '/dmp/crowd-list',
  path: '/dmp/crowd-list',
  getParentRoute: () => rootRouteImport,
} as any)
const CrowdManageRoute = CrowdManageRouteImport.update({
  id: '/crowd/manage',
  path: '/crowd/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsFlowAnalysisRoute = AnalyticsFlowAnalysisRouteImport.update({
  id: '/analytics/flow-analysis',
  path: '/analytics/flow-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingPlanRoute = AdvertisingPlanRouteImport.update({
  id: '/advertising/plan',
  path: '/advertising/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingCampaignRoute = AdvertisingCampaignRouteImport.update({
  id: '/advertising/campaign',
  path: '/advertising/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingAdvertisersRoute = AdvertisingAdvertisersRouteImport.update({
  id: '/advertising/advertisers',
  path: '/advertising/advertisers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertising/advertisers': typeof AdvertisingAdvertisersRoute
  '/advertising/campaign': typeof AdvertisingCampaignRoute
  '/advertising/plan': typeof AdvertisingPlanRoute
  '/analytics/flow-analysis': typeof AnalyticsFlowAnalysisRoute
  '/crowd/manage': typeof CrowdManageRoute
  '/dmp/crowd-list': typeof DmpCrowdListRoute
  '/tools/white-list': typeof ToolsWhiteListRoute
  '/advertising': typeof AdvertisingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertising/advertisers': typeof AdvertisingAdvertisersRoute
  '/advertising/campaign': typeof AdvertisingCampaignRoute
  '/advertising/plan': typeof AdvertisingPlanRoute
  '/analytics/flow-analysis': typeof AnalyticsFlowAnalysisRoute
  '/crowd/manage': typeof CrowdManageRoute
  '/dmp/crowd-list': typeof DmpCrowdListRoute
  '/tools/white-list': typeof ToolsWhiteListRoute
  '/advertising': typeof AdvertisingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertising/advertisers': typeof AdvertisingAdvertisersRoute
  '/advertising/campaign': typeof AdvertisingCampaignRoute
  '/advertising/plan': typeof AdvertisingPlanRoute
  '/analytics/flow-analysis': typeof AnalyticsFlowAnalysisRoute
  '/crowd/manage': typeof CrowdManageRoute
  '/dmp/crowd-list': typeof DmpCrowdListRoute
  '/tools/white-list': typeof ToolsWhiteListRoute
  '/advertising/': typeof AdvertisingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertising/advertisers'
    | '/advertising/campaign'
    | '/advertising/plan'
    | '/analytics/flow-analysis'
    | '/crowd/manage'
    | '/dmp/crowd-list'
    | '/tools/white-list'
    | '/advertising'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertising/advertisers'
    | '/advertising/campaign'
    | '/advertising/plan'
    | '/analytics/flow-analysis'
    | '/crowd/manage'
    | '/dmp/crowd-list'
    | '/tools/white-list'
    | '/advertising'
  id:
    | '__root__'
    | '/'
    | '/advertising/advertisers'
    | '/advertising/campaign'
    | '/advertising/plan'
    | '/analytics/flow-analysis'
    | '/crowd/manage'
    | '/dmp/crowd-list'
    | '/tools/white-list'
    | '/advertising/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertisingAdvertisersRoute: typeof AdvertisingAdvertisersRoute
  AdvertisingCampaignRoute: typeof AdvertisingCampaignRoute
  AdvertisingPlanRoute: typeof AdvertisingPlanRoute
  AnalyticsFlowAnalysisRoute: typeof AnalyticsFlowAnalysisRoute
  CrowdManageRoute: typeof CrowdManageRoute
  DmpCrowdListRoute: typeof DmpCrowdListRoute
  ToolsWhiteListRoute: typeof ToolsWhiteListRoute
  AdvertisingIndexRoute: typeof AdvertisingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising/': {
      id: '/advertising/'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/white-list': {
      id: '/tools/white-list'
      path: '/tools/white-list'
      fullPath: '/tools/white-list'
      preLoaderRoute: typeof ToolsWhiteListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmp/crowd-list': {
      id: '/dmp/crowd-list'
      path: '/dmp/crowd-list'
      fullPath: '/dmp/crowd-list'
      preLoaderRoute: typeof DmpCrowdListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowd/manage': {
      id: '/crowd/manage'
      path: '/crowd/manage'
      fullPath: '/crowd/manage'
      preLoaderRoute: typeof CrowdManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/flow-analysis': {
      id: '/analytics/flow-analysis'
      path: '/analytics/flow-analysis'
      fullPath: '/analytics/flow-analysis'
      preLoaderRoute: typeof AnalyticsFlowAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising/plan': {
      id: '/advertising/plan'
      path: '/advertising/plan'
      fullPath: '/advertising/plan'
      preLoaderRoute: typeof AdvertisingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising/campaign': {
      id: '/advertising/campaign'
      path: '/advertising/campaign'
      fullPath: '/advertising/campaign'
      preLoaderRoute: typeof AdvertisingCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising/advertisers': {
      id: '/advertising/advertisers'
      path: '/advertising/advertisers'
      fullPath: '/advertising/advertisers'
      preLoaderRoute: typeof AdvertisingAdvertisersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertisingAdvertisersRoute: AdvertisingAdvertisersRoute,
  AdvertisingCampaignRoute: AdvertisingCampaignRoute,
  AdvertisingPlanRoute: AdvertisingPlanRoute,
  AnalyticsFlowAnalysisRoute: AnalyticsFlowAnalysisRoute,
  CrowdManageRoute: CrowdManageRoute,
  DmpCrowdListRoute: DmpCrowdListRoute,
  ToolsWhiteListRoute: ToolsWhiteListRoute,
  AdvertisingIndexRoute: AdvertisingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
